#普通数据的配置
name: zhangsan

#对象的配置
#person:
#  name: zhangsan
#  age: 18
#  addr: beijing
#行内对象配置
person: {name: zhangsan,age: 18, addr: beijing}

#配置数据 集合
city:
  - beijing
  - tianjin
  - chongqing
  - shanghai
#city: [beijing,tianjin,chongqing,shanghai]

student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 19
    addr: chongqing

#student: [{name: tom,age: 18,addr: beijing},{name: lucy,age: 19,addr: chongqing}]

#Map配置
map:
  key1: value1
  key2: value2

